### ISSUE TITLE
VirusTotal module hangs, errors

### ISSUE THREAD

**Issue by KDPryor** [woj-ciech/Danger-zone#4]
Loving this tool. However, running a --domain search it got to where it hit the VirusTotal API limit and went to sleep for 70 seconds. It hung there indefinitely. I hit the space bar and got the following error:

`----------------VirusTotal module---------------------------
API limitation, putting into sleep for 70 sec
[*] Domain was resolved to following IPs:
 207.210.240.140 on 2015-09-04 00:00:00
-------------------WhoIs history module---------------------
[*} Found 0 result(s)
Traceback (most recent call last):
  File "./Danger-zone.py", line 230, in <module>
    tools.save_graph(G, domain)
  File "/mnt/c/users/ken/Documents/GitHub/Danger-zone/tools.py", line 74, in save_graph
    nx.draw(G, with_labels=True)  # ,edge_colors=colors)
  File "/usr/local/lib/python2.7/dist-packages/networkx/drawing/nx_pylab.py", line 112, in draw
    cf = plt.gcf()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by woj-ciech** [comment]
I didn't approach this kind of error, are you using some remote machine? It seems like there is no display device to use.
Please try to follow this advice https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

**Comment by KDPryor** [comment]
That did fix this problem. Thanks!
